### ISSUE TITLE
Api usage

### ISSUE THREAD

**Issue by sefakilic006** [christophebe/julius-gpt#1]
I installed like 
`npm install julius-gpt -S`
And I am trying to use like your readme example but when I run js file like `node main.js` it exists with error code 1 and output is

```
Usage: julius [options] [command]

Generate and publish your content from the command line 🤯

Options:
  -V, --version   output the version number
  -h, --help      display help for command

Commands:
  post [options]  Generate a post
  wp              Wordpress related commands. The wp list is stored in the local store : ~/.julius/wordpress.json
  help [command]  display help for command
```
So how can I run with js file?
Package.json file
>{
  "type": "module",
  "dependencies": {
    "julius-gpt": "^0.0.8"
  }
}

main.js file is same as readme example

**Comment by christophebe** [comment]
Indeed, there is an issue to use the API. We need to work on it. 
You are welcome to provide a patch. 

There is not yet a stable version at the moment. 

Thanks

**Comment by christophebe** [comment]
Make a try with the version 0.0.11. It should work now. 
I have also updated the readme for the API section.
